import PDFDocument from "pdfkit";

export interface PdfTable {
  title: string;
  subtitle?: string;
  columns: string[];
  rows: (string | number)[][];
  totalsRow?: (string | number)[];
  /** Summary lines rendered as a section after the table. */
  summary?: string[];
}

/** Server-side PDF generation (pdfkit) — no client dependency. */
export function renderTablePdf(table: PdfTable): Promise<Buffer> {
  return new Promise((resolvePromise, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      layout: "landscape",
      bufferPages: true, // needed for "Page X of Y" footers
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolvePromise(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).text(table.title, { align: "left" });
    if (table.subtitle) {
      doc.moveDown(0.25).fontSize(10).fillColor("#666666").text(table.subtitle);
    }
    doc.moveDown(0.75).fillColor("#000000");

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const colWidth = pageWidth / table.columns.length;
    const rowHeight = 22;
    let y = doc.y;

    const drawRow = (cells: (string | number)[], bold: boolean) => {
      if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
        y = doc.page.margins.top;
      }
      doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(9);
      cells.forEach((cell, i) => {
        doc.text(String(cell), doc.page.margins.left + i * colWidth + 4, y + 6, {
          width: colWidth - 8,
          ellipsis: true,
        });
      });
      doc
        .moveTo(doc.page.margins.left, y + rowHeight)
        .lineTo(doc.page.margins.left + pageWidth, y + rowHeight)
        .strokeColor("#dddddd")
        .stroke();
      y += rowHeight;
    };

    drawRow(table.columns, true);
    for (const row of table.rows) drawRow(row, false);
    if (table.totalsRow) drawRow(table.totalsRow, true);

    // Summary section (with a page break guard)
    if (table.summary && table.summary.length > 0) {
      if (y + 60 > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
        y = doc.page.margins.top;
      }
      y += 16;
      doc
        .font("Helvetica-Bold")
        .fontSize(11)
        .fillColor("#000000")
        .text("Summary", doc.page.margins.left, y);
      y += 18;
      doc.font("Helvetica").fontSize(9).fillColor("#333333");
      for (const line of table.summary) {
        if (y + 14 > doc.page.height - doc.page.margins.bottom) {
          doc.addPage();
          y = doc.page.margins.top;
        }
        doc.text(`• ${line}`, doc.page.margins.left + 8, y);
        y += 14;
      }
    }

    // Footer on every page: product credit + page numbers.
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .fillColor("#999999")
        .text(
          `Generated by My Event Planner — ${new Date().toISOString().slice(0, 10)}`,
          doc.page.margins.left,
          doc.page.height - doc.page.margins.bottom + 10,
          { lineBreak: false },
        )
        .text(
          `Page ${i + 1} of ${range.count}`,
          doc.page.width - doc.page.margins.right - 70,
          doc.page.height - doc.page.margins.bottom + 10,
          { lineBreak: false },
        );
    }
    doc.end();
  });
}
